#!/usr/bin/env ruby
require 'chunky_png'

world = ARGV[0].nil? ? World.last : World.find(ARGV[0])
file_name = ARGV[1] || "doc/world_pngs/#{world.id}-#{world.name.gsub(/\s/, '_')}.png"

canvas = ChunkyPNG::Image.new world.width, world.height, ChunkyPNG::Color(139,69,19)

tile_total = world.width * world.height
batches = tile_total / 1000
batch_count = 0
puts 'Generating PNG...'
ResourceTile.where(:world_id => world.id).find_in_batches do |group|
  batch_count += 1
  print("  PNG %d%%".green.and_go_to(0) % ((batch_count * 100.0) / batches))
  group.each do |rt|
    y, x = rt.location
    case rt.type
    when WaterTile.to_s
      canvas[x,y] = ChunkyPNG::Color :blue
    when LandTile.to_s
      if rt.tree_density > 0.01
        color = ChunkyPNG::Color.rgba(139 - (rt.tree_density * 139).to_i, (rt.tree_density * 100).to_i + 69, 19, 255)
        canvas[x,y] = color
      end
    end
  end
end
puts "  PNG 100%             ".green

canvas.save file_name
puts file_name
system("open #{file_name}")
